### ISSUE TITLE
Alspro exits with code 1 when environment variable HOME is unset

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#101]
Examples (`env -u` unsets a variable before running):

```
$ env -u HOME alspro
ALS Prolog (Threaded) Version 3.3.1 [darwin]
   Copyright (c) 1987-2017 Applied Logic Systems, Inc.
Setting up library indicies...may take a moment...Done.
$ echo $?
1
```

Ultimately, alspro should be able to run without any environment:

```
$ env -i /usr/local/bin/alspro
ALS Prolog (Threaded) Version 3.3.1 [darwin]
   Copyright (c) 1987-2017 Applied Logic Systems, Inc.

Setting up library indicies...may take a moment...Done.

$ echo $?
1
```

Note: add a new command-line test to cover this issue before fixing.

**Comment by kenbowen** [comment]
A few phi_writes show that it dies in core/alsp_src/builtins/blt_shl.pro, on the getenv call in the clause
setup_history_file(home, HistoryFile)
        :-!,
        getenv('HOME', UserHomePath),
        ........

which runs in the main start_shell0 setup of the shell.

**Comment by kenbowen** [comment]
Towards the goal of running with no env:

In ~builtins:
KB-SSD > grep 'getenv(' *
blt_dvsh.pro:        getenv('HOME', UserHomePath),
blt_dvsh.pro:	getenv('HOME', HomeDir),
blt_shl.pro:        getenv('HOME', UserHomePath),
blt_shl.pro:	(getenv('ALSPATH',ALSPATH) ->
blt_shl.pro:	getenv('HOME',HOME),
blt_shlc.pro:	(getenv('ALS_LIBS', EnvLibsString) ->
blt_shlc.pro:	getenv('HOME', HomePath),
blt_std.pro:	getenv(Name,Value),
blt_sys.pro:	(getenv('SHELL', Shell) ; getenv('COMSPEC', Shell)),
blt_sys.pro:	getenv('SHELL', Shell),
blt_sys.pro:	getenv('HOME', Home),
filepath.pro:	(After = 0 -> getenv('HOME', Home) ; get_user_home(Name, Home)),

All of the non-‘HOME’ calls to getenv are protected either by explicit conditionals (->) or conditionals in the form of multiple clauses with cuts in the right places.  However, in the line in filepath.pro [it’s in tilda_expand/2], if the getenv('HOME', Home) fails and there is no environment, get_user_home(Name, Home) may or may not get in trouble due to it’s call on record = getpwnam(name) in ~generic/bos.c in pbi_get_user_home.  If just fails, that’s ok, since then tilda_expand is idempotent: tilda_expand(Path, Path).

So it seems possible that working out how to handle getenv('HOME', Home) when there is no ‘HOME’ env var set might in fact allow alspro/alsdev to run with no env whatsoever.

**Comment by kenbowen** [comment]
If the ‘HOME’ env variable is unset, I think I would propose that getenv succeed with either the alsdir folder, or create a ‘user’ subdir of alsdir:  alsdir/user.  It would be easy to add clauses for getenv either in bos.c, or in prolog.  For the latter, in built.c, change

	BLT("getenv", 2, pbi_getenv, "_pbi_getenv"),
to
	BLT("getenv0”, 2, pbi_getenv, "_pbi_getenv"),

and then define getenv from getenv0 using:

?- builtins:sys_searchdir(Path).

Path='/Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/alsdir/'
