### ISSUE TITLE
alsdev: Edit > Clear has no effect without selection

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#40]
Choose File > New, type something, and then choose Edit > Clear.  Nothing happens.
However, it some of the typed text is selected, that is removed when Edit > Clear is chosen.
     Note: this also applies to the main alsdev console as well as the debugger console.
Should change 'Clear' to 'Clear Selection'.

**Comment by chuckhoupt** [comment]
`Edit > Delete` seems to be the standard terminology these days (see Mac TextEdit.app or Win Notepad.exe). I committed a fix for that at f19b67b4d5543233793fe33b25c59b4678df5d87

The real bug here is that the menu item should only be active when there is a selection (standard behavior for native apps). Unfortunately, Tk doesn't have any build-in support for menu-enabling (i.e. syncing text selection state with menu enable states), so one would have to create a mechanism to do that.

**Comment by kenbowen** [comment]
Edit > Delete fix by https://github.com/AppliedLogicSystems/ALSProlog/commit/f19b67b4d5543233793fe33b25c59b4678df5d87; superseded by #41
