### ISSUE TITLE
Add File>Examples and support for read-only example files

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#54]
Usually, there are two issues with read-only example files:

- The example files may be stored in non-obvious locations (/usr/share/doc or inside an .app bundle, etc).
- The example files are read-only, so changes cannot be saved.

### Finding example files

Typically, to make example files more discoverable a program will add some helper UI. For example, in [Scratch], there is an example button in the File>Open dialog. In [Xynk], there is a File>Examples>* sub-menu that lists all examples (stored in the .app bundle).

For alsdev, a simple solution would be to add a menu item like File>Examples..., which would just present the standard open-file dialog, but always set to browse /usr/share/doc/als-prolog/examples (or wherever).

### Saving modified example files

Once a read-only example file is found and opened, the problem is what to do with modifications. Rather then display a write-denied error message, programs like [Scratch] and [Xynk] will offer to save the modified example somewhere else. Basically, the Save command always triggers Save-As, often defaulting the location to a standard "Documents" folder in the user's home directory.

For alsdev, it might be necessary to add a flag to any file window opened from examples, to signal that it should use Save-As if it needs saving.

## Impact of Docs

With the above solutions, tutorial docs became much easier and consistent. Because the examples have some helper UI, docs just need to say "open queens.pro from File>Examples..." and the user will find it every time. Because the examples are read-only, a user following a tutorial is always guaranteed to get a pristine copy of the example, even if they previously played around with it (and broke it).

[ note, the above applies to the alsdev GUI. Command-line users of alspro just need pointers to /usr/share/doc/als-prolog/examples in the man page, etc. They can just `cp -r` the examples if they want to tinker with them. ]

[Scratch]: https://scratch.mit.edu
[Xynk]: https://xynkapp.com

**Comment by kenbowen** [comment]
File>Examples and “Save command always triggers Save-As, often defaulting the location to a standard "Documents" folder in the user's home directory.” make sense to me.  

“For alsdev, it might be necessary to add a flag to any file window opened from examples, to signal that it should use Save-As if it needs saving” is also sensible, because the user might have navigated to the examples folder directly rather than from File>Examples.

Much of what is in builtins/library could also be considered useful as examples, or is rather experimental in character, e.g., pxml.pro and friends.  We might want to treat the library similarly to examples, e.g. File>Library, and a flag to signal Save-As.  However, I don’t think we want to conflate the Library with the Examples in this. 

The Library was always conceived of as somewhat dynamic, with useful code sometimes being added as it developed in the course of building apps.  So I think it might be good to have a way of copying modified or newly developed files back into the library.  Of course, a person would have to have the right permissions.  But I don’t think it should be Save-As.  More like “Copy To Library”, with prompts about “Do you really want to do this?”

Actually, in a teaching situation, the same kind of copy back might be useful for Examples too.  But I think that while Examples and Library might be pretty much parallel, they should be kept separate.

**Comment by kenbowen** [comment]
If we add a copy-back facility to either Library or Examples, we might want to do an auto-backup whenever the incoming file was over-writing an existing one.

**Comment by kenbowen** [comment]
Fixed via f4b01cfd1fe07edde111b7e1023d10cf04b073d1
