### ISSUE TITLE
Homebrew alspro exits immediately when .alspro is present

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#78]
Setup: Install Homebrew als-prolog 3.2.0

Any .alspro file causes alspro to immediately exit. For example, in a empty directory do:

```
$ touch .alspro
$ alspro
ALS Prolog (Threaded) Version 09f863b (tag: v3.2.0) [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

$ echo $?
1
```

**Comment by kenbowen** [comment]
> On Sep 11, 2016, at 2:14 PM, Chuck Houpt <notifications@github.com> wrote:
> 
> An empty .alspro file (0 bytes) causes alspro to immediately exit. For example, in a empty directory do:
> 
> $ touch .alspro
> $ alspro
> ALS Prolog .... [immediate exit]
> $ echo $?
> 1
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Definitely odd & confusing.  Here’s on my system (in branch * i2-alspro-line-edit):

Nothing in HOME:
KB-SSD > pwd
/Users/ken
KB-SSD > ls -a .als*
ls: .als*: No such file or directory

Now in ~/darwin:
KB-SSD > pwd
/Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin
KB-SSD > ls -a .als*
.alspro
KB-SSD > ls -l .alspro
-rw-r--r--+ 1 ken  staff  0 Sep 11 14:32 .alspro
KB-SSD > ./alspro
ALS Prolog (Threaded) Version 3.2.0-36-g47c38fd [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

Attempting to consult .alspro...
... consulted /Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/.alspro
?- 

Check touch:
KB-SSD > rm .alspro
KB-SSD > ls -l .alspro
ls: .alspro: No such file or directory
KB-SSD > touch .alspro
KB-SSD > ./alspro
ALS Prolog (Threaded) Version 3.2.0-36-g47c38fd [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

Attempting to consult .alspro...
... consulted /Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/.alspro
?- 

Since you’re not even seeing the banner, I’m suspicious of what’s happening.  The banner is printed before it tries to do anything with .alspro.  Try ‘make distclean’ and go to ~/darwin ??

—Ken

**Comment by chuckhoupt** [comment]
Updated report to show that full banner is displayed before exit.

**Comment by kenbowen** [comment]
Commit 7f00655 on branch i2-alspro-line-edit fixes this.  However, email from Chuck (below) suggests simpler code (so I'll leave this issue open for now):

If you end up rewriting the last commit, you might consider removing the new DotALSPresent argument because I don't think it is necessary. For the history settings, it doesn't really matter if a dot-alspro was present or not. For example, You could set the history file location like this:

check_setup_history_file(HistoryFile) :-
   user:history_file_locn(HFL) ; HFL = home,
   setup_history_file(HFL, HistoryFile).

The OR takes care of switching between the default (home) and possible user setting. I think that would simplify things alot.

**Comment by chuckhoupt** [comment]
Actually, there were two bugs here that got mixed up. A short-term bug on branch i2-alspro-line-edit (which is fixed) and a long-term bug that is found in the Homebrew package of 3.2.0.

Since the branch bug is fixed, I'm going to adjust this issue to explicitly describe the Homebrew/3.2.0 bug.

**Comment by kenbowen** [comment]
Handled by https://github.com/AppliedLogicSystems/ALSProlog/commit/843ab7c44bfa69068ba4e30e370390ce8984ce16
